[versions]
jackson2 = "2.21.0"
jackson3 = "3.0.4"
kotlin = "2.3.0"
kotlinXCoroutines = "1.10.2"
qosLogback = "1.5.27"
qosSlf4j = "2.0.17"
reactorKotlin = "1.3.0"
snakeYaml = "2.6"
springBoot = "4.0.0-RC1"
springDoc = "3.0.0-RC1"

[libraries]
jackson2-module = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson2" }
jackson3-module = { group = "tools.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson3" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinXCoroutines" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "kotlinXCoroutines" }
qos-logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "qosLogback" }
qos-slf4j-bridge = { group = "org.slf4j", name = "jul-to-slf4j", version.ref = "qosSlf4j" }
reactor-kotlin = { group = "io.projectreactor.kotlin", name = "reactor-kotlin-extensions", version.ref = "reactorKotlin" }
spring-boot-autoconfigure = { group = "org.springframework.boot", name = "spring-boot-autoconfigure", version.ref = "springBoot" }
spring-boot-jackson = { group = "org.springframework.boot", name = "spring-boot-jackson", version.ref = "springBoot" }
spring-boot-reactor = { group = "org.springframework.boot", name = "spring-boot-reactor", version.ref = "springBoot" }
spring-boot-reactor-netty = { group = "org.springframework.boot", name = "spring-boot-reactor-netty", version.ref = "springBoot" }
spring-boot-webflux = { group = "org.springframework.boot", name = "spring-boot-webflux", version.ref = "springBoot" }
spring-boot-devtools = { group = "org.springframework.boot", name = "spring-boot-devtools", version.ref = "springBoot" }
springdoc-webflux-api = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-api", version.ref = "springDoc" }
springdoc-webflux-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-ui", version.ref = "springDoc" }
yaml-snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeYaml" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
